/**
 * activityStore - NeuBridge Activity State (Zustand)
 *
 * Manages the daily queue, in-progress activity sessions,
 * and completion tracking. The queue is generated by the
 * ai-daily-queue Edge Function and cached locally for the day.
 */
import { create } from 'zustand';
import { supabase } from '../lib/supabase';
import type { ActivityType, DailyQueueItem, ActivityResult, DiseaseStage, MoodType } from '../types';

interface ActivityState {
  // Daily queue
  queue: DailyQueueItem[];
  completedToday: Set<ActivityType>;
  queueDate: string | null; // ISO date string
  isLoadingQueue: boolean;

  // Current session
  currentActivity: ActivityType | null;
  sessionStartTime: Date | null;

  // Actions
  loadDailyQueue: (patientId: string, stage: DiseaseStage, mood: MoodType) => Promise<void>;
  startActivity: (activity: ActivityType) => void;
  completeActivity: (patientId: string, result: ActivityResult, stage: DiseaseStage, mood?: MoodType) => Promise<void>;
  resetQueue: () => void;
}

export const useActivityStore = create<ActivityState>((set, get) => ({
  queue: [],
  completedToday: new Set(),
  queueDate: null,
  isLoadingQueue: false,
  currentActivity: null,
  sessionStartTime: null,

  loadDailyQueue: async (patientId, stage, mood) => {
    const today = new Date().toISOString().split('T')[0];

    // If queue is already loaded for today, don't reload
    if (get().queueDate === today && get().queue.length > 0) return;

    set({ isLoadingQueue: true });

    try {
      // Check Supabase for today's AI-generated queue
      const { data: existing } = await supabase
        .from('ai_adjustments')
        .select('*')
        .eq('patient_id', patientId)
        .gte('created_at', `${today}T00:00:00`)
        .order('created_at', { ascending: false })
        .limit(1)
        .single();

      let queue: DailyQueueItem[] = [];

      if (existing?.daily_queue?.daily_queue) {
        queue = existing.daily_queue.daily_queue;
      } else {
        // Generate new queue via Edge Function
        const { data: { session } } = await supabase.auth.getSession();
        if (session) {
          const response = await supabase.functions.invoke('ai-daily-queue', {
            body: { patient_id: patientId, stage, mood },
          });
          if (response.data?.daily_queue) {
            queue = response.data.daily_queue;
          }
        }
      }

      // Load today's completions
      const { data: sessions } = await supabase
        .from('activity_sessions')
        .select('activity')
        .eq('patient_id', patientId)
        .eq('completed', true)
        .gte('created_at', `${today}T00:00:00`);

      const completed = new Set<ActivityType>(
        (sessions ?? []).map((s: any) => s.activity as ActivityType)
      );

      set({
        queue,
        completedToday: completed,
        queueDate: today,
        isLoadingQueue: false,
      });
    } catch (e) {
      set({ isLoadingQueue: false });
    }
  },

  startActivity: (activity) => {
    set({ currentActivity: activity, sessionStartTime: new Date() });
  },

  completeActivity: async (patientId, result, stage, mood) => {
    const { sessionStartTime } = get();
    const durationSeconds = sessionStartTime
      ? Math.floor((Date.now() - sessionStartTime.getTime()) / 1000)
      : result.duration_seconds;

    // Log to Supabase
    await supabase.from('activity_sessions').insert({
      patient_id: patientId,
      activity: result.activity,
      stage_at_time: stage,
      difficulty_params: result.score,
      score: result.score,
      duration_seconds: durationSeconds,
      completed: result.completed,
      mood_at_start: mood ?? null,
      completed_at: result.completed ? new Date().toISOString() : null,
    });

    // Also log analytics event
    await supabase.from('analytics_events').insert({
      patient_id: patientId,
      event_type: 'activity_complete',
      event_data: { activity: result.activity, duration_seconds: durationSeconds, completed: result.completed },
    }).then(() => {}, () => {}); // Non-blocking

    set((state) => ({
      completedToday: new Set([...state.completedToday, result.activity]),
      currentActivity: null,
      sessionStartTime: null,
    }));
  },

  resetQueue: () => set({
    queue: [],
    completedToday: new Set(),
    queueDate: null,
    currentActivity: null,
    sessionStartTime: null,
  }),
}));
